/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hzg_wpn_nexus_libpniio_jni_LibpniioJni */

#ifndef _Included_hzg_wpn_nexus_libpniio_jni_LibpniioJni
#define _Included_hzg_wpn_nexus_libpniio_jni_LibpniioJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    createFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_createFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_openFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_closeFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write__JLjava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write__JLjava_lang_String_2J
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write__JLjava_lang_String_2F
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write__JLjava_lang_String_2D
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write_and_grow
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write_1and_1grow__JLjava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write_and_grow
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write_1and_1grow__JLjava_lang_String_2J
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write_and_grow
 * Signature: (JLjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write_1and_1grow__JLjava_lang_String_2F
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write_and_grow
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write_1and_1grow__JLjava_lang_String_2D
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    write_and_grow
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_write_1and_1grow__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
