/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hzg_wpn_nexus_libpniio_jni_LibpniioJni */

#ifndef _Included_hzg_wpn_nexus_libpniio_jni_LibpniioJni
#define _Included_hzg_wpn_nexus_libpniio_jni_LibpniioJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hzg_wpn_nexus_libpniio_jni_LibpniioJni
 * Method:    createFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hzg_wpn_nexus_libpniio_jni_LibpniioJni_createFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
