/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitbucket_ingvord_pnijni_LibpniioJni */

#ifndef _Included_org_bitbucket_ingvord_pnijni_LibpniioJni
#define _Included_org_bitbucket_ingvord_pnijni_LibpniioJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitbucket_ingvord_pnijni_LibpniioJni
 * Method:    createFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bitbucket_ingvord_pnijni_LibpniioJni_createFile
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
